{% set name = "simplejson" %}
{% set version = "3.20.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5fe7a6ce14d1c300d80d08695b7f7e633de6cd72c80644021874d985b3393649

build:
  number: 0
  script:
    - export REQUIRE_SPEEDUPS=1  # [not win]
    - set REQUIRE_SPEEDUPS=1  # [win]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    #- {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - simplejson
    - simplejson._speedups   # [python_impl != 'pypy']
    - simplejson.tests
  commands:
    - pip check
    - pytest --pyargs simplejson.tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/simplejson/simplejson
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Simple, fast, extensible JSON encoder/decoder for Python
  description: |
    simplejson is a simple, fast, complete, correct and extensible
    JSON <https://json.org> encoder and decoder for Python 2.5+ and
    Python 3.3+. It is pure Python code with no dependencies, but includes
    an optional C extension for a serious speed boost.
  doc_url: https://simplejson.readthedocs.io
  dev_url: https://github.com/simplejson/simplejson

extra:
  recipe-maintainers:
    - ainafp
    - ocefpaf
