appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: DOPz25mmTGRrjFVnAiY9xWX3qpurErx2zGozguid9bste6ep7jGH4Hc3neNORm7bcYgxDgrjUjxonvFIZe+i4nDfzr+Mo0tMPnTjbAHWYRhPu+V4BnnjsR9ZWMioztrWmOW5lGGQoRKMF+bsrdpj3jPzLjo2vFyavGmFhU3WH6PfZ3oOyyH8r9IsbUzE3EqZlMfNWQ2YOSMwXU5LIbKPiPhRodLeNxQS3YwlmjmBWEsEG8Vs7B10XmNLm4Dz/dW2TAxN0Smqjy0BO/vF2oZENxrwY/W0FhrRwNGPOAJWH4rP2IfoO7/N6WnWX89So5DrTTFAOcxIyaul2H4rM+HBXIUjoXfbL1kUGLg5pXc0DiT19eHOdRQJZEKrlYv7oXZxlcIoKV1sqe4I89HOhpfGuayfbU7F2fE3g86QcoJmIBy7GYTfQsixxf6WahbjMqXVK7EP7bsHltj64PfaPscuVrGZzQjgLchAiP/D0TvcIokv7Z3C3R5Z/CD8ea1bYebIf+LnLeZa1TSMQLAiRvLXr8P9Oyfq+CQQWzKKDrANmkCS8Q3DDfRul5vNhz1mB482fg58DAD780kiewDlaGtCkzLApNawNrGPKtY9DNVihGgJymMZD+DiabNIkXO4VS4azrDIB+HNbOvDcSv317YNuPo42+P1eUmqDOhIkWVc1W8=}
