travis:
  secure:
    BINSTAR_TOKEN: X1IiHhSCbVYVOAh1d+60xuyaAGDwvU5UAWl1emVpNZ670g7tpIspV5zvp4r17zD9q9tDupT4nRDCTdZUtsOg06rwmSFPTg/7lb0qBroWUsC2ILvQikPaE/FCiQ/M2Pi5NSxUiPL8hoS/gA5nW9Xdf49v1MsQB1fioIKS2V322HoyRyoIQWBE3KF8ZM1PQMCZ/hgExcrIT1n6KKMPrrUifufh99RJEGnVPyQWwlL9tmoVNRdWzLAGbZj7sMfqMTW7JOEIy82NXT/T765lvImpN0sK67Kk+PNhDXUs8WtneeWPh2YPVCXiM3cHYHR0vo8ZHxKx9wS2/xRjzIVsX1X+m3XVNPaZ5s5QfyqGJ4/2klIjln+eaWJW0zAEP55BOM0I0bHPwk8qnCHLty4T/AwaMwQgDp03RIZzYCFvNOob06KHoQl+UPr8yBj8I2bbLXuCiILiunubdTLkY0lK7gIHaBaPqJ4fGkGRefiGrKUL4Iwj6is1nI+9i12e2vEWdyYGkW+OEZj3GPZFNN0SDhUst2WbWPvEk/3qQurutlmlkb+9PNOo0DFZ3ns8KqephXLZ0WMIHCT+2HhX6fBwUNREkqCQKQpf5dTAeKxQ2n3BD+IOOHKUB4NmumHdm0ly52ShSI0Y034Y6WiRdBX9ei4VfV8ZpFCQB9M9dLrzxnFJOh0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
