travis:
  secure:
    BINSTAR_TOKEN: G9pX36kx3sN9QdVfnTyWgmy+UGPK9M7xQuanxDRujudKHSXQOVWfMVhfEvAL7gaiPx5ICzq331lXre8NDr5SgHx485KswiZ0GYumz34xH9jaK/a03ta0kpUtfDWm8qsZwEQ124BFJVmHIgV6xIjiiQ9mwDJeXtDuUPxMgeDArUlz33KI5dVlvJSWdh77iKBdUqycdQtYoBBpUAZ/XsrK8Tx1HfSAbXaaFKhqVw9azxw7noBTiMZ8ofWrn0NkxqEwJho5UE0g01k/5Pa4bLk97eK6eITl3kitNGbL6xo7SvD5wyuTAeqBA4iNlNOJO90ePUZd3EXgcnic8vgAd6yG1ksC684VxPocv7CiTB22AZXQH/jSIfS2JdwBoihQ3J4bcjjd5bXfoMdE5bHrsBvYaNGLJPIboubpP1WQJ8BU+VYT4LvsfGn1SVfcY0HyFjbvUiTLtK3+0bly40I9Q833Ak0NK6f+QMX3kstcIlx6diCG3tCR5CVwp8U9SOpSoveXRYqYdEoAvS9Zze/rzOkUukm6bMt/Qo5gOiZXwFBuA6kLOYtAEXZ2Uy6iaJ5/XxM4ZRp5g45LfadUNutfQGKnSQEjR6bjYzPd6MCe/NWlBa5tzCl3Nj0ng0WSYbdXjNj8U71M2QtsuMsTA8mxOwvPV9nrYL3v9G1C/aOxd4mY0/0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
